export const copy = {
  title: "הרשימה",
  titleEn: "List Draft",
  tagline: "דראפט לרשימה, ואז ליל בחירות.",
  sponsor: "אב־טיפוס עצמאי · לא תחזית",
  disclosure:
    "זה צעצוע, לא סקר ולא תחזית ל־27 באוקטובר 2026. אף מפלגה לא תומכת במשחק. רשימה מעורבת כאן אינה ברית אמיתית.",
  nLabel: "מספר מפלגות יריבות",
  levelLabel: "רמת קושי",
  start: "התחל דראפט",
  modeLabel: "מצב",
  modeDraft: "דראפט",
  modeDraftHint: "בחר עשרה שמות מהבריכה.",
  modeCreate: "צור מנהיג",
  modeCreateHint: "צייר ראש על הצירים, ואז שבץ תשעה.",
  modeDaily: "אתגר היום",
  modeDailyHint: (name: string) => `היום משחקים עם ${name}.`,
  createTitle: "הראש שלך",
  createLede: "שם שאתה ממציא, וחמישה צירים. לא פוליטיקאי אמיתי, לא סקר.",
  createName: "שם",
  createNamePh: "למשל איתי",
  createStart: "התחל עם הראש הזה",
  createClash: "השם הזה כבר בבריכה. בחר שם אחר — בלי להעתיק פנים אמיתיות.",
  createNearest: "המשבצת הקרובה",
  createBack: "חזרה",
  axisLow: {
    bibi: "לא־ביבי",
    judicial: "בג״ץ",
    service: "שירות",
    security: "מתון",
    economy: "שוק",
  },
  axisHigh: {
    bibi: "נתניהו",
    judicial: "רפורמה",
    service: "פטור",
    security: "קשה",
    economy: "מדינה",
  },
  share: "העתק קישור",
  shared: "הקישור הועתק",
  boardTitle: "לוח שיאים",
  boardLocal: "על המכשיר הזה קודם. כשיש שרת — מתמזג ברקע, בלי מסך טעינה. לא ספירת שחקנים.",
  boardEmpty: "עוד אין ריצה. סיימו דראפט, מנהיג או אתגר — והשורה תופיע כאן.",
  boardOpen: "לוח שיאים",
  noBoard: "על המכשיר הזה קודם. לא ספירת שחקנים.",
  firstPlace: (name: string, seats: number) =>
    `${name} במקום הראשון עם ${seats} מנדטים. אפשר לנצח אותו?`,
  noFirstPlace: "עוד אין שיא במצב הזה. סיימו משחק — והשם יופיע כאן.",
  playerName: "שם השחקן",
  partyName: "שם המפלגה",
  anonPlayer: "שחקן",
  boardHub: "ראש הרשימה",
  playWith: (name: string) => `שחק עם ${name}`,
  yourTurn: "התור שלך",
  cpuTurn: (n: number) => `תור מפלגה ${n}`,
  cpuThinking: "המפלגה בוחרת…",
  cpuNotice: (party: string, name: string, slot: number) =>
    `${party} שבצה את ${name} בבחירה ${slot}`,
  roundNotices: "הסבב",
  party: (n: number) => `מפלגה ${n}`,
  yourParty: "המפלגה שלך",
  parties: "מפלגות",
  pickN: (n: number, max: number) => `בחירה ${n} מתוך ${max}`,
  confirm: (name: string) => `שבץ את ${name}`,
  confirmEmpty: "סמן שם ואז שבץ",
  cell: "תא",
  draw: "משיכה",
  toy: "צעצוע",
  edgesToHub: "קצוות מול ראש הרשימה",
  noHub: "בחר ראש רשימה — הוא הרכז.",
  source: "מקור",
  edgeHoverHint: "רחף על קו.",
  colorRed: "אדום: סתירה",
  colorGreen: "ירוק: אותה שורה",
  colorScale: "צבע הקו = חוזק החיבור, לא כן/לא",
  colorScaleVeto: "וטו",
  colorScaleFar: "מחנות",
  colorScaleNone: "אפור",
  colorScaleClose: "אותה שורה",
  sideTone: "הפס בצד = מול כל הרשימה, משוקלל",
  sideToneHint: "ראש הרשימה שוקל יותר. וטו מול הראש נשאר אדום.",
  metersLive: "מתעדכנים בכל בחירה",
  noWikiPhoto: "אין תמונה חופשית בוויקיפדיה",
  aspectLegend: "נתניהו · משפט · שירות · ביטחון · כלכלה",
  pipExplain: "חמשת הפסים מתחת לשם: נתניהו, משפט, שירות, ביטחון, כלכלה. כמה גבוה הפס — יותר בצד הזה. פרופיל במשחק, לא סקר.",
  slot: "מקום",
  compatible: "מתאים לרכז",
  opposed: "סותר את הרכז",
  unknown: "לא ידוע",
  pool: "הבריכה",
  chooseParty: "בחר מפלגה",
  chooseMember: "בחר שם",
  chooseMemberHint: "קודם מפלגה, אחר כך שם.",
  backToParties: "← חזרה לכל המפלגות",
  noHubAfter: "שבץ שם נוסף לרשימה.",
  night: "ליל בחירות",
  seats: "מנדטים",
  credibility: "אמינות",
  demand: "ביקוש",
  credibilityTip: "כמה הרשימה נשמעת כמו מפלגה אחת. ריב בין הראש לסגן הורס את זה.",
  demandTip: "כמה קולות נשארו לרשימה. אם מפלגה אחרת יושבת באותו גוש — הן חולקות את הקולות.",
  afterSplit: "קולות שנשארו אחרי שמפלגות דומות חלקו",
  winBySeats: "מנצחת המפלגה עם הכי הרבה מנדטים.",
  threshold: "אחוז חסימה 3.25%",
  dropped: "לא עבר",
  win: "ניצחון",
  loss: "הפסד",
  why: "למה",
  replay: "שחק שוב",
  emptySlot: "פנוי",
  taken: "נלקח",
  axisX: "שירות / חילוני ← → חרדי",
  axisY: "מחנה השינוי ← → גוש נתניהו",
  aspects: "פרופיל",
  aspectsToy: "פרופיל צעצוע — לא סקר",
  twoScores: "שני ציונים, לא אחד — כמה זה נשמע כמו מפלגה, וכמה קולות נשארו.",
  howCalcTitle: "איך זה עובד",
  howCalcAria: "איך מחשבים את הציונים",
  howCalcBlocks: [
    {
      title: "השמות",
      body: "האנשים אמיתיים — מתוך עשרת הראשונים שפורסמו לכל מפלגה ב־2026. לא המצאנו פוליטיקאים. תמונה מוויקיפדיה כשיש דף וצילום חופשי; חיפוש מטושטש רק אם שם המשפחה (ולפעמים גם הפרטי) מופיע בכותרת — בלי לצרף פנים אחרות. לטליק גואילי ולשמות חדשים בלי דף — כרטיס ראשי־תיבות, לא תצלום מעיתון.",
      links: [
        {
          label: "רשימות 2026",
          url: "https://en.wikipedia.org/wiki/Party_lists_for_the_2026_Israeli_legislative_election",
        },
      ],
    },
    {
      title: "העץ — אמינות",
      body: "חמשת הפסים תחת השם הם ציר נתניהו, משפט, שירות, ביטחון וכלכלה — פרופיל צעצוע, לא סקר. הכלכלה היא גורם CHES-Israel (lrecon) ברמת מפלגה: גבוה = יותר מדינה וחלוקה. היא צובעת כימיה בלבד; גבעת הביקוש נשארת שירות × ביבי. כשמשווים שני אנשים — משווים אותם, לא את שתי המפלגות. לוין מול קריב זה לא אותו דבר כמו כהן מול קריב. הפס הצבעוני בצד השם הוא מול כל הרשימה הנוכחית, משוקלל לפי מקום (ראש הרשימה ×1.25). קווי העץ הם כל הזוגות: הצבע רציף מאדום וטו (s=−1) דרך אפור (0) עד ירוק קל (s=+0.22), והעובי לפי המקומות ברשימה. אמינות וביקוש למעלה מתעדכנים אחרי כל בחירה, עם צמיחת עמודה וספירת מספר — תנועה, לא סקר. יש וטו ששובר הכול, קרע, מתח, שמועות, וגם ירוק כששייכים לאותו מחנה. מי שאין עליו קו ציבורי נשאר ממוצע המפלגה עם הטיה לפי תפקיד. ריב בין 1 ל־2 הורס כרזה; ריב בין 5 ל־6 כמעט לא נשמע. זה משחק, כולל שמועות. זה לא תיק, לא סקר, ולא כמה הם הצביעו ביחד בכנסת.",
      links: [
        {
          label: "ליברמן / נתניהו",
          url: "https://www.timesofisrael.com/liveblog_entry/liberman-vows-not-to-join-any-coalition-with-netanyahu-or-raam-well-establish-a-zionist-government/",
        },
        {
          label: "ליברמן / רע״ם",
          url: "https://www.jpost.com/israel-news/politics-and-diplomacy/article-884505",
        },
        {
          label: "בנט / שירות",
          url: "https://www.jpost.com/israel-news/politics-and-diplomacy/article-891845",
        },
      ],
    },
    {
      title: "הגבעה — ביקוש",
      body: "כל אחד יושב על מפה גסה: נתניהו או לא, שירות או חרדים, וכו'. הרשימה נופלת על גבעה. אם שתי מפלגות יושבות על אותה גבעה — הן גונבות אחת לשנייה קולות. המספרים כאן מצוירים, לא מתוך סקר של הערב.",
      links: [
        { label: "CHES-Israel, להשראה", url: "https://www.chesdata.eu/chesisrael" },
      ],
    },
    {
      title: "המנדטים",
      body: "לוקחים את הגבעה, מכפילים כמה הכרזה מחזיקה, וקצת את כוח הראש. מי שלא עובר 3.25% יוצא. אחר כך מחלקים 120 כיסאות. מי עם הכי הרבה — ניצח.",
    },
    {
      title: "בקיצור",
      body: "צעצוע. לא תחזית ל־27 באוקטובר, לא עיתון, לא ברית אמיתית. אף מפלגה לא תומכת במשחק.",
    },
  ],
};

export const roleHe = {
  leader: "מנהיג",
  minister: "שר",
  mk: "ח״כ",
  newcomer: "חדש",
} as const;

export const edgeTypeHe = {
  veto: "וטו",
  split: "פיצול",
  "same-faction": "אותה סיעה",
  "served-together": "כיהנו יחד",
  "cell-distance": "מרחק תאים",
  personal: "שמועה",
} as const;
